[phases.setup]
nixPkgs = [
  "php84",
  "php84Packages.composer",
  "nodejs_20",
  "php84Extensions.gd",
  "php84Extensions.zip",
  "php84Extensions.mbstring",
  "php84Extensions.pdo",
  "php84Extensions.pdo_mysql",
  "php84Extensions.bcmath",
  "php84Extensions.fileinfo"
]

[phases.build]
cmds = [
  "mkdir -p .composer",
  "composer install --optimize-autoloader --no-dev --ignore-platform-reqs",
  "npm install",
  "npm run build"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

